services:
- type: web
  name: server
  runtime: image
  image:
    url: twentycrm/twenty:latest
  dockerCommand: "sh -c ./scripts/render-run.sh"
  autoDeploy: false
  plan: FREE
  envVars:
    - key: FRONT_BASE_URL
      fromService:
        name: server
        type: web
        envVarKey: RENDER_EXTERNAL_URL
    - key: SERVER_URL
      fromService:
        name: server
        type: web
        envVarKey: RENDER_EXTERNAL_URL
    - key: APP_SECRET
      generateValue: true
    - key: PG_DATABASE_HOST
      fromService:
        name: twenty_postgres
        type: pserv
        property: host
    - key: PG_DATABASE_PORT
      fromService:
        name: twenty_postgres
        type: pserv
        property: port
    - key: IS_BILLING_ENABLED
      value: "true"
    - key: BILLING_STRIPE_API_KEY
      sync: false
    - key: BILLING_STRIPE_WEBHOOK_SECRET
      sync: false
    - key: BILLING_PLAN_REQUIRED_LINK
      sync: false
    - key: OPENAI_API_KEY
      sync: false
    - key: ANTHROPIC_API_KEY
      sync: false
    - key: XAI_API_KEY
      sync: false
    - key: IS_MULTIWORKSPACE_ENABLED
      value: "true"
    - key: DEFAULT_SUBDOMAIN
      value: "app"
    - key: EMAIL_DRIVER
      value: "SMTP"
    - key: EMAIL_SMTP_HOST
      sync: false
    - key: EMAIL_SMTP_PORT
      value: "587"
    - key: EMAIL_SMTP_USER
      sync: false
    - key: EMAIL_SMTP_PASSWORD
      sync: false
    - key: EMAIL_FROM_ADDRESS
      value: "noreply@yourcompany.com"
    - key: EMAIL_FROM_NAME
      value: "Twenty Team"
    - key: STORAGE_TYPE
      value: "S3"
    - key: STORAGE_S3_REGION
      value: "us-east-1"
    - key: STORAGE_S3_NAME
      sync: false
    - key: STORAGE_S3_ACCESS_KEY_ID
      sync: false
    - key: STORAGE_S3_SECRET_ACCESS_KEY
      sync: false
    - key: REDIS_URL
      sync: false
    - key: AUTH_PASSWORD_ENABLED
      value: "true"
    - key: IS_EMAIL_VERIFICATION_REQUIRED
      value: "true"
- type: worker
  name: worker
  runtime: image
  image:
    url: twentycrm/twenty:latest
  dockerCommand: "sh -c ./scripts/render-worker.sh"
  autoDeploy: false
  plan: STARTER
  envVars:
    - key: FRONT_BASE_URL
      fromService:
        name: server
        type: web
        envVarKey: RENDER_EXTERNAL_URL
    - key: SERVER_URL
      fromService:
        name: server
        type: web
        envVarKey: RENDER_EXTERNAL_URL
    - key: APP_SECRET
      generateValue: true
    - key: PG_DATABASE_HOST
      fromService:
        name: twenty_postgres
        type: pserv
        property: host
    - key: PG_DATABASE_PORT
      fromService:
        name: twenty_postgres
        type: pserv
        property: port
  disk:
    name: twenty-disk
    mountPath: /.local-storage
    sizeGB: 5
- type: pserv
  name: twenty_postgres
  plan: STARTER
  runtime: image
  image:
    url: twentycrm/twenty-postgres:latest
  autoDeploy: false
  disk:
    name: data
    mountPath: /var/lib/postgresql/data
    sizeGB: 10
  envVars:
  - key: POSTGRES_USER
    value: postgres
  - key: POSTGRES_PASSWORD
    value: postgres
